from collections import defaultdict

# The game name
NAME = "Bartholos"

# The interface used by the Server to run its webserver/SocketIO on.
SERVER_INTERFACE = "0.0.0.0"
# The port used by the server for its webserver.
SERVER_PORT = 8000

# The interface used by the portal for its listening ports.
PORTAL_INTERFACE = "0.0.0.0"
# The port that the portal will use for telnet.
PORTAL_TELNET = 7999

PORTAL_URL_TO_GAME = "http://127.0.0.1:8000"

# Classes that the server will use for various things.
SERVER_CLASSES = dict()
SERVER_CLASSES["core"] = "bartholos.server.core.Core"
SERVER_CLASSES["game_session"] = "bartholos.server.game_session.GameSession"
SERVER_CLASSES["python_parser"] = "bartholos.server.repl.PythonParser"
SERVER_CLASSES["login_parser"] = "bartholos.server.login.LoginParser"
SERVER_CLASSES["main_menu_parser"] = "bartholos.server.main_menu.MainMenuParser"

PORTAL_CLASSES = dict()
PORTAL_CLASSES["core"] = "bartholos.portal.portal.Core"

PORTAL_SERVICES = {"telnet": "bartholos.portal.telnet.TelnetService"}

PORTAL_EVENT_HANDLER_MODULES = ["bartholos.portal.events"]

AUTOPROXY_PATHS: dict[str, list[str]] = defaultdict(list)


OPTIONS_ACCOUNT_DEFAULT = {
    "border_style": ["Headers, footers, table borders, etc.", "Style", "magenta"],
    "header_style": [
        "Headers generated by Rich.",
        "Style",
        "bold",
    ],
    "timezone": ["Timezone for dates.", "Timezone", "UTC"],
    "screenreader": [
        "Minimize fancy formatting.",
        "Boolean",
        False,
    ],
}

# Modules holding Option classes, responsible for serializing the option and
# calling validator functions on it. Same-named functions in modules added
# later in this list will override those added earlier.
OPTION_CLASS_MODULES = ["bartholos.utils.optionclasses"]
# Module holding validator functions. These are used as a resource for
# validating options, but can also be used as input validators in general.
# Same-named functions in modules added later in this list will override those
# added earlier.
VALIDATOR_FUNC_MODULES = ["bartholos.utils.validatorfuncs"]

LOG_DIR = "logs"
