from mudforge.settings_default import *
from collections import defaultdict


SERVER_HOOKS = {
    "early_launch": [
        "bartholos.server.hooks.setup_django",
        "bartholos.server.hooks.import_validatorfuncs",
        "bartholos.server.hooks.import_optionclasses",
    ]
}

SERVER_CLASSES["game_session"] = "bartholos.server.game_session.GameSession"
SERVER_CLASSES["python_parser"] = "bartholos.server.repl.PythonParser"
SERVER_CLASSES["login_parser"] = "bartholos.server.login.LoginParser"
SERVER_CLASSES["main_menu_parser"] = "bartholos.server.main_menu.MainMenuParser"


PROXY_PATHS: dict[str, list[str]] = defaultdict(list)


COMMODITY_CURRENCY_KEY = "coin"


OPTIONS_ACCOUNT_DEFAULT = {
    "border_style": ["Headers, footers, table borders, etc.", "Style", "magenta"],
    "header_style": [
        "Headers generated by Rich.",
        "Style",
        "bold",
    ],
    "timezone": ["Timezone for dates.", "Timezone", "UTC"],
    "screenreader": [
        "Minimize fancy formatting.",
        "Boolean",
        False,
    ],
}

# Modules holding Option classes, responsible for serializing the option and
# calling validator functions on it. Same-named functions in modules added
# later in this list will override those added earlier.
OPTION_CLASS_MODULES = ["bartholos.utils.optionclasses"]
# Module holding validator functions. These are used as a resource for
# validating options, but can also be used as input validators in general.
# Same-named functions in modules added later in this list will override those
# added earlier.
VALIDATOR_FUNC_MODULES = ["bartholos.utils.validatorfuncs"]
